version: "3.8"
services:
  app:
    build: .
    container_name: plex-donate
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    networks:
      - media-net
networks:
  media-net:
    external: true
